version: '3'
services:
  main-api:
    container_name: main-api
    environment:
      - DATABASE_HOST=postgres
      - MONGO_DB_CONNECTION=mongodb://root:password@mongodb:27017/
    depends_on:
      - database
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - main-network
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
  database:
    container_name: postgres
    image: 'postgres'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'postgres'
    networks:
      - main-network
    volumes:
      - database-data:/var/lib/postgresql/data/
  mongo:
    container_name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - main-network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - database
    ports:
      - '5555:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    networks:
      - main-network
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data:
networks:
  main-network:
