version: '3'
services:
  main-api:
    container_name: main-api
    depends_on:
      - database
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - main-network
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
  database:
    image: 'postgres' # use latest official postgres version
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'postgres'
    networks:
      - main-network
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - database
    ports:
      - '5555:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    networks:
      - main-network
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose
networks:
  main-network:
